version: '3.8'

services:
  denira-parser:
    build:
      context: .  # Путь к Dockerfile
      dockerfile: Dockerfile  # Можно опустить, если Dockerfile находится в корне
    image: denira-parser:latest
    container_name: denira-parser
    stdin_open: true
    tty: true
    volumes:
      - ./chatId.txt:/app/chatId.txt
      - ./.env:/app/.env 
      - ./lastNearestDate.txt:/app/lastNearestDate.txt  # Сохранение lastNearestDate.txt
